# Generated by Django 5.0.2 on 2025-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_leaderboard_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
