# Generated by Django 5.0.2 on 2025-03-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_alter_leaderboard_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='questions',
        ),
    ]
