# Generated by Django 5.0.2 on 2025-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='start_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
