# Generated by Django 5.0.2 on 2025-03-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_player_score_player_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='start_time',
        ),
    ]
